#!/bin/bash

set -Ee

test_cmd() {
    local cmd=$1
    local exp_rc=$2
    local exp_stdout=$3
    local exp_stderr=$4

    actual_stdout_file=$(mktemp)
    actual_stderr_file=$(mktemp)

    echo "Running $cmd. Expecting RC=$exp_rc, stdout='$exp_stdout', stderr='$exp_stderr'"
    set +e
    eval "$cmd" >"${actual_stdout_file}" 2>"${actual_stderr_file}"
    actual_rc=$?
    set -e

    if [[ "${actual_rc}" -ne "${exp_rc}" ]] || \
	    ([[ -n "${exp_stdout}" ]] && ! grep -qP "${exp_stdout}" "${actual_stdout_file}") || \
	    ([[ -n "${exp_stderr}" ]] && ! grep -qP "${exp_stderr}" "${actual_stderr_file}"); then

        echo "FAIL..."
        echo "Actual RC=$actual_rc"
	echo "--- stdout ---"
	cat "${actual_stdout_file}"
	echo "--- stderr ---"
	cat "${actual_stderr_file}"
	echo "--------------"
	exit 1
    fi
    echo "OK"
}

# base usage
test_cmd "usg"            2  "Available commands are"        ""
test_cmd "usg --help"     0  "Available commands are"        ""
test_cmd "usg --version"  0  "\d*\.\d*\.\d*"                 ""

# cis_level1_server profile should exist
test_cmd "usg list --all"                            0  "cis_level1_server"             ""
test_cmd "usg list --all | grep 'Listing all available'" 0  "Listing all available profiles"             ""

# machine-readable flag should print "profile:type:product:..." and no extra information
test_cmd "usg list --machine-readable"                            0  ":cis_level1_server:CIS:"             ""
test_cmd "usg list --machine-readable | grep 'Listing all available'" 1  ""                              ""

# get list of all available profile names
all_profiles=($(usg list --machine --all | cut -d: -f1 | sort -u | xargs))

# ensure cis_level1_server exists
test_cmd "echo ${all_profiles} | grep -w cis_level1_server-v1.0.0"  0  "cis_level1_server-v1.0.0"

# commands without special args should work for all profiles
for profile in ${all_profiles[@]}
do
    # test that info shows correct benchmark type
    case $profile in
        cis_*) btype=CIS; cac_id=${profile/-v*/}
            ;;
        stig*) btype=STIG; cac_id=${profile/-v*/}
            ;;
        *) btype=UNKNOWN
    esac
    test_cmd "usg info '$profile'"  0  "Benchmark.*$btype"   ""

    # test that generate tailoring works
    test_cmd "usg generate-tailoring $profile $profile.xml"  0  ""  "USG generate-tailoring command completed."
    test_cmd "grep \"$cac_id\" $profile.xml"  0  "<Profile id=" ""

    # test that generate fix works
    test_cmd "usg generate-fix $profile"  0  ""  "Wrote remediation script to '${cac_id}-.*sh'"
    test_cmd "grep 'BEGIN fix' ${cac_id}-*.sh"  0  "BEGIN fix" ""

    # generate-fix with tailoring file
    test_cmd "usg generate-fix -t $profile.xml -o fix.sh"  0  ""  "Wrote remediation script to.*fix.sh"
    test_cmd "grep 'BEGIN fix' fix.sh"  0  "BEGIN fix" ""

    # test that audit starts when using profile (full run is too long and useless, timeout at 2s)
    test_cmd "timeout 2 usg audit $profile"  124  "Rule.*xccdf_org.ssgproject.content_rule"  ""
    test_cmd "timeout 2 usg audit -t $profile.xml"  124  "Rule.*xccdf_org.ssgproject.content_rule"  ""

    rm -f *xml *sh
    rm -rf /var/lib/usg/*
done

# ensure known aliases resolve correctly
if grep -w "stig" <<<"${all_profiles[@]}"; then
    test_cmd "usg info stig | grep '^Profile.* stig-v1r1' " 0 "stig-v1r1"
    test_cmd "usg info disa_stig | grep '^Profile.* stig-v1r1' " 0 "stig-v1r1"
fi
test_cmd "usg info cis_level1_server | grep '^Profile.* cis_level1_server-v1.0.0' " 0 "cis_level1_server-v1.0.0"

# generate tailoring file with version v1.0.0
test_cmd "usg generate-tailoring cis_level1_server-v1.0.0 t1.xml"  0  "" "generate-tailoring command completed."
test_cmd "grep href t1.xml"  0  "href=" ""

# customize tailoring file on the host for quick audit/fix
sed -e 's/"true"/"false"/g' \
    -e '/file_owner_etc_shadow\|disable_users_coredumps/ s/"false"/"true"/g' \
    -i t1.xml

# test info cmd with tailoring file, without tailoring/profile and with default tailoring file
test_cmd "usg info -t t1.xml"  0  "Benchmark.*CIS"  ""
test_cmd "usg info"  2  ""  "a profile or a tailoring file must be provided"
mkdir -p /etc/usg/ && cp t1.xml /etc/usg/default-tailoring.xml
test_cmd "usg info"  0  ""  "Using the default tailoring file"
rm /etc/usg/default-tailoring.xml

# Audit with tailoring file, should be 1 pass, 1 fail
rm -f /var/lib/usg/* /var/log/usg.log
test_cmd "usg audit -t t1.xml"  0  ""  "USG audit scan command completed."
test_cmd "grep -P 'Fail:\s+1,' /var/log/usg.log"  0  "Fail" ""
test_cmd "grep -P 'Pass:\s+1,' /var/log/usg.log"  0  "Pass" ""
# Ensure default outputs exist
test_cmd "test -s /var/lib/usg/usg-report-*.html"  0  "" ""
test_cmd "test -s /var/lib/usg/usg-results-*.xml"  0  "" ""
# Ensure non-default outputs exist
rm -f /var/lib/usg/* /var/log/usg.log report.html results.xml
test_cmd "usg audit -t t1.xml --html-file report.html --results-file results.xml --debug --oval-results"  0  ""  "USG audit scan command completed."
test_cmd "grep -P 'Fail:\s+1,' /var/log/usg.log"  0  "Fail" ""
test_cmd "grep -P 'Pass:\s+1,' /var/log/usg.log"  0  "Pass" ""
test_cmd "test -s report.html"  0  "" ""
test_cmd "test -s results.xml"  0  "" ""
test_cmd "test -s /var/lib/usg/usg-log-*log"  0  "" ""
test_cmd "test -s /var/lib/usg/ssg-ubuntu????-oval.xml.result-*.xml"  0  "" ""
test_cmd "test -s /var/lib/usg/ssg-ubuntu????-cpe-oval.xml.result-*.xml"  0  "" ""


# Fix with tailoring file, only failed rules
rm -f /var/lib/usg/* /var/log/usg.log
test_cmd "usg fix -t t1.xml --only-failed"  0  "" "USG fix command completed"
# test only one rule is in remediation script
test_cmd "grep -c BEGIN /var/lib/usg/*sh"  0  "^1$"  ""

# Re-audit to confirm remediation
rm -f /var/lib/usg/* /var/log/usg.log
test_cmd "usg audit -t t1.xml"  0  ""  "USG audit scan command completed"
test_cmd "grep -P 'Fail:\s+0,' /var/log/usg.log"  0  "Fail" ""
test_cmd "grep -P 'Pass:\s+2,' /var/log/usg.log"  0  "Pass" ""


# Fix with tailoring file, all rules
rm -f /var/lib/usg/*
test_cmd "usg fix -t t1.xml"  0  "" "USG fix command completed"
# test both rules are in remediation script
test_cmd "grep -c BEGIN /var/lib/usg/*sh"  0  "^2$"  ""
# Ensure default outputs exist
test_cmd "test -s /var/lib/usg/usg-report-*.html"  0  "" ""
test_cmd "test -s /var/lib/usg/usg-results-*.xml"  0  "" ""
# Ensure non-default outputs exist
rm -f /var/lib/usg/* report.html results.xml
test_cmd "usg fix -t t1.xml --html-file report.html --results-file results.xml --debug --oval-results"  0  ""  "USG fix command completed"
test_cmd "test -s report.html"  0  "" ""
test_cmd "test -s results.xml"  0  "" ""
test_cmd "test -s /var/lib/usg/usg-log-*log"  0  "" ""
test_cmd "test -s /var/lib/usg/ssg-ubuntu????-oval.xml.result-*.xml"  0  "" ""
test_cmd "test -s /var/lib/usg/ssg-ubuntu????-cpe-oval.xml.result-*.xml"  0  "" ""


# test that the legacy usg fallback runs ok and fails due to missing benchmark bundle
mv /usr/bin/python3 /root/
test_cmd "usg generate-fix cis_level1_server"   1   "legacy USG"  "Error: could not find any benchmark bundle installed"

# mock the benchmark bundle (usg-benchmarks-1) which would is normally installed as recommended pkg from esm
# (create dir, copy first datastream, decompress and unpack, rename some files...)
bdir=/usr/share/ubuntu-scap-security-guides/current/benchmarks
mkdir -p $bdir
pushd $bdir >/dev/null
cp /usr/share/usg-benchmarks/ubuntu*CIS_1/ssg*ds.xml.gz ./
gunzip ssg*gz
oscap ds sds-split ssg*ds.xml ./
for f in scap_org.*xml; do mv $f ${f/scap_org.open-scap_cref_/}; done
popd >/dev/null
test_cmd "usg generate-fix cis_level1_server"   0   "legacy USG" "USG generate-fix command completed."
# revert
mv /root/python3 /usr/bin/

