#!/bin/sh
#
# Ubuntu Security Guide
# Copyright 2025 Canonical Ltd.
#
# SPDX-License-Identifier: GPL-3.0-only
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
# Wrapper for USG module in /usr/share/usg

USG_BASE_DIR="/usr/share/usg"
PYTHON3=/usr/bin/python3

if [ ! -x "${PYTHON3}" ]; then
  echo
  echo "********************* WARNING *********************"
  echo "Could not find python interpreter at ${PYTHON3}."
  echo
  echo "Using legacy USG and outdated benchmarks as fallback."
  echo "Some functionality might not be available."
  echo "***************************************************"
  echo
  $USG_BASE_DIR/legacy/usg "$@"
  exit $?
fi

if [ ! -d "${USG_BASE_DIR}/usg" ]; then
  echo "Fatal! Could not find usg module in ${USG_BASE_DIR}. Please reinstall the usg package."
  exit 1
fi

PYTHONPATH="$USG_BASE_DIR" "${PYTHON3}" -m usg "$@"
