#!/bin/sh
# Wrapper for USG module in /usr/share/usg

USG_BASE_DIR="/usr/share/usg"
PYTHON3=/usr/bin/python3

if [ ! -x "${PYTHON3}" ]; then
  echo
  echo "********************* WARNING *********************"
  echo "Could not find python interpreter at ${PYTHON3}."
  echo
  echo "Using legacy USG and outdated benchmarks as fallback."
  echo "Some functionality might not be available."
  echo "***************************************************"
  echo
  $USG_BASE_DIR/legacy/usg "$@"
  exit $?
fi

if [ ! -d "${USG_BASE_DIR}/usg" ]; then
  echo "Fatal! Could not find usg module in ${USG_BASE_DIR}. Please reinstall the usg package."
  exit 1
fi

PYTHONPATH="$USG_BASE_DIR" "${PYTHON3}" -m usg "$@"
